In [141]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [142]:
loan = pd.read_csv('data/loan_data.csv')

loan.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [143]:
loan.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             601 non-null    object
 2   Married            611 non-null    object
 3   Dependents         599 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      582 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         592 non-null    float64
 9   Loan_Amount_Term   600 non-null    float64
 10  Credit_History     564 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [144]:
loan.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [145]:
loan.describe()

,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History
count,614.000000,614.000000,592.000000,600.00000,564.000000
mean,5403.459283,1621.245798,146.412162,342.00000,0.842199
std,6109.041673,2926.248369,85.587325,65.12041,0.364878
min,150.000000,0.000000,9.000000,12.00000,0.000000
25%,2877.500000,0.000000,100.000000,360.00000,1.000000
50%,3812.500000,1188.500000,128.000000,360.00000,1.000000
75%,5795.000000,2297.250000,168.000000,360.00000,1.000000
max,81000.000000,41667.000000,700.000000,480.00000,1.000000

In [ ]:
# Handling missing Data

In [146]:
# Filling the missing values

fill_values = {
    "Gender":loan["Gender"].mode()[0],
    "Married":loan["Married"].mode()[0],
    "Dependents":loan["Dependents"].mode()[0],
    "Self_Employed":loan["Self_Employed"].mode()[0],
    "LoanAmount":loan["LoanAmount"].median(),
    "Loan_Amount_Term":loan["Loan_Amount_Term"].median(),
    "Credit_History":loan["Credit_History"].mode()[0]
}

In [147]:
filled = loan.fillna(fill_values)

filled.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [148]:
filled.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Loan_ID            614 non-null    object
 1   Gender             614 non-null    object
 2   Married            614 non-null    object
 3   Dependents         614 non-null    object
 4   Education          614 non-null    object
 5   Self_Employed      614 non-null    object
 6   ApplicantIncome    614 non-null    int64
 7   CoapplicantIncome  614 non-null    float64
 8   LoanAmount         614 non-null    float64
 9   Loan_Amount_Term   614 non-null    float64
 10  Credit_History     614 non-null    float64
 11  Property_Area      614 non-null    object
 12  Loan_Status        614 non-null    object
dtypes: float64(4), int64(1), object(8)
memory usage: 62.5+ KB

In [149]:
filled.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [150]:
X = filled.drop(columns=['Loan_ID', 'Loan_Status'], axis=1)
y = filled['Loan_Status']

In [151]:
filled.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [152]:
X.isnull().sum()

Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
dtype: int64

In [153]:
X['Gender']= X['Gender'].map({'Female':0, 'Male':1})
X['Married'] = X['Married'].map({'No':0, 'Yes': 1})
X['Education'] = X["Education"].map({'Graduate':0, 'Not Graduate':1})
X["Self_Employed"]= X["Self_Employed"].map({'No':0, 'Yes':1})
X['Property_Area'] = X['Property_Area'].map({'Urban':0,'Rural':1, 'Semiurban':2})

In [154]:
y = filled['Loan_Status'].map({'Y': 0, 'N': 1})

In [155]:
X.replace(to_replace="3+", value=4, inplace=True)

In [156]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, stratify=y)

In [157]:
scale_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
scaler = StandardScaler()
X_train[scale_cols] = scaler.fit_transform(X_train[scale_cols])
X_test[scale_cols] = scaler.transform(X_test[scale_cols])

In [158]:
log_model = LogisticRegression(max_iter=5000)

log_model.fit(X_train, y_train)

LogisticRegression(max_iter=5000)

In [159]:
log_pred = log_model.predict(X_test)

log_accuracy = accuracy_score(
    y_test,
    log_pred
)
print("Logistic Accuracy", log_accuracy)

Logistic Accuracy 0.8130081300813008

In [161]:
print("Training data:", X_train.isnull().sum().sum())
print("Testing data:", X_test.isnull().sum().sum())

Training data: 0
Testing data: 0

In [163]:
print(classification_report(y_test, log_pred))

              precision    recall  f1-score   support

           0       0.80      0.96      0.88        85
           1       0.86      0.47      0.61        38

    accuracy                           0.81       123
   macro avg       0.83      0.72      0.74       123
weighted avg       0.82      0.81      0.79       123

In [164]:
print("\nConfusion Matrix:\n", confusion_matrix(y_test, log_pred))

Confusion Matrix:
 [[82  3]
 [20 18]]

In [165]:
from sklearn.feature_selection import SelectKBest, chi2

selector = SelectKBest(score_func=chi2, k=5)
X_selected = selector.fit(X, y)


dfscores = pd.DataFrame(X_selected.scores_)
dfcolumns = pd.DataFrame(X.columns)
featureScores = pd.concat([dfcolumns, dfscores], axis=1)
featureScores.columns = ['Features', 'Score'] 
featureScores.nlargest(7, 'Score')

             Features         Score
6   CoapplicantIncome  11342.041603
5     ApplicantIncome     93.904964
7          LoanAmount     32.821655
9      Credit_History     26.005877
10      Property_Area      4.398854
8    Loan_Amount_Term      3.778554
3           Education      3.540502

In [166]:
from sklearn.feature_selection import SelectKBest, chi2
# Apply SelectKBest with chi-squared test (for categorical/boolean features
selector = SelectKBest(score_func=chi2, k=4) # chi2 requires non-negative value
X_selected = selector.fit(X, y)

dfscores = pd.DataFrame(X_selected.scores_)
dfcolumns = pd.DataFrame(X.columns)
featureScores = pd.concat([dfcolumns, dfscores], axis=1)
featureScores.columns = ['Specs', 'Score'] # Naming the dataframe column
featureScores.nlargest(10, 'Score') # Print the top 10 features
# print("Selected feature indices:", selector.get_support(indices=True))

                Specs         Score
6   CoapplicantIncome  11342.041603
5     ApplicantIncome     93.904964
7          LoanAmount     32.821655
9      Credit_History     26.005877
10      Property_Area      4.398854
8    Loan_Amount_Term      3.778554
3           Education      3.540502
1             Married      1.782425
0              Gender      0.036234
4       Self_Employed      0.007285

In [174]:
# Let's make some prediction

new_data = pd.DataFrame({
    'Gender': [1],
    'Married': [0],
    'Dependents': [0],
    'Education': [0],
    'Self_Employed': [0],
    'ApplicantIncome': [5000],
    'CoapplicantIncome': [1],
    'LoanAmount': [1000],
    'Loan_Amount_Term': [200],
    'Credit_History': [1],
    'Property_Area': [2]
})

prediction = log_model.predict(new_data)
print(f"Prediction for new data: {'YES' if prediction[0] == 1 else 'NO'}")

Prediction for new data: NO

In [171]:
pred_probability = log_model.predict_proba(new_data)
pred_probability

array([[1.00000000e+000, 2.97594681e-101]])

In [172]:
new_data = pd.DataFrame({
    'Gender': [1],
    'Married': [0],
    'Dependents': [0],
    'Education': [1],
    'Self_Employed': [0],
    'ApplicantIncome': [5000],
    'CoapplicantIncome': [0],
    'LoanAmount': [1000],
    'Loan_Amount_Term': [200],
    'Credit_History': [0],
    'Property_Area': [2]
})

prediction = log_model.predict(new_data)
print(f"Prediction for new data: {'YES' if prediction[0] == 1 else 'NO'}")

Prediction for new data: NO

In [176]:
pred_probability = log_model.predict_proba(new_data)
pred_probability

array([[1.00000000e+000, 1.93201838e-101]])